// Command generate compiles the pinned contexts and property descriptions.
package main

import (
	"bytes"
	"encoding/csv"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"os"
	"sort"
	"strings"
)

type definition struct {
	ID        string `json:"@id"`
	Type      string `json:"@type"`
	Container string `json:"@container"`
}

const (
	generatedFileMode = 0o644
	propertyColumns   = 4
)

type contextDocument struct {
	Context map[string]json.RawMessage `json:"@context"`
	Graph   json.RawMessage            `json:"@graph"`
}

func main() {
	if err := run("internal/contexts", "terms_generated.go"); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
func run(dir, output string) error {
	input, err := os.Open(dir + "/properties_description.csv")
	if err != nil {
		return err
	}
	ranges, err := readRanges(input)
	closeErr := input.Close()
	if err != nil {
		return err
	}
	if closeErr != nil {
		return closeErr
	}
	var out strings.Builder
	out.WriteString("// Code generated by go generate; DO NOT EDIT.\n\npackage codemeta\n\nvar contextTerms = map[Version]map[string]termDefinition{\n")
	for _, version := range []string{"2.0", "3.0", "master"} {
		data, err := os.ReadFile(dir + "/" + version + ".jsonld")
		if err != nil {
			return err
		}
		defs, prefixes, err := readContext(data)
		if err != nil {
			return err
		}
		fmt.Fprintf(&out, "%q: {\n", version)
		for _, name := range sortedKeys(defs) {
			def := defs[name]
			iri, err := expand(def.ID, prefixes)
			if err != nil {
				return err
			}
			coercion, err := expand(def.Type, prefixes)
			if err != nil {
				return err
			}
			propertyKey := ""
			if prefix, local, ok := strings.Cut(def.ID, ":"); ok {
				propertyKey = prefix + ":" + local
			}
			prefix := prefixes[name] != ""
			fmt.Fprintf(&out, "%q: {iri:%q, coercion:%q, container:%q, prefix:%t, expected:%q},\n", name, iri, coercion, def.Container, prefix, ranges[propertyKey])
		}
		out.WriteString("},\n")
	}
	out.WriteString("}\n")
	formatted, err := format.Source([]byte(out.String()))
	if err != nil {
		return err
	}
	return os.WriteFile(output, formatted, generatedFileMode)
}
func sortedKeys[T any](m map[string]T) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}
func readContext(data []byte) (map[string]definition, map[string]string, error) {
	var doc contextDocument
	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&doc); err != nil {
		return nil, nil, err
	}
	if len(doc.Context) == 0 {
		return nil, nil, fmt.Errorf("missing context")
	}
	defs := map[string]definition{}
	prefixes := map[string]string{}
	for name, raw := range doc.Context {
		if strings.HasPrefix(name, "@") {
			return nil, nil, fmt.Errorf("unsupported context keyword %q", name)
		}
		var simple string
		var def definition
		if json.Unmarshal(raw, &simple) == nil {
			def.ID = simple
			if strings.HasSuffix(simple, "/") || strings.HasSuffix(simple, "#") {
				prefixes[name] = simple
			}
		} else {
			decoder := json.NewDecoder(bytes.NewReader(raw))
			decoder.DisallowUnknownFields()
			if err := decoder.Decode(&def); err != nil {
				return nil, nil, fmt.Errorf("%s: %w", name, err)
			}
		}
		if def.ID == "" {
			return nil, nil, fmt.Errorf("%s: missing @id", name)
		}
		if def.Container != "" && def.Container != "@list" && def.Container != "@set" {
			return nil, nil, fmt.Errorf("%s: unsupported container %s", name, def.Container)
		}
		defs[name] = def
	}
	return defs, prefixes, nil
}
func expand(value string, prefixes map[string]string) (string, error) {
	if value == "" || value == "@id" || value == "@type" || strings.HasPrefix(value, "http://") || strings.HasPrefix(value, "https://") {
		return value, nil
	}
	prefix, name, ok := strings.Cut(value, ":")
	if !ok || prefixes[prefix] == "" {
		return "", fmt.Errorf("unsupported context expression %q", value)
	}
	return prefixes[prefix] + name, nil
}
func readRanges(r io.Reader) (map[string]string, error) {
	rows, err := csv.NewReader(r).ReadAll()
	if err != nil {
		return nil, err
	}
	if len(rows) == 0 || strings.Join(rows[0], ",") != "Parent Type,Property,Type,Description" {
		return nil, fmt.Errorf("unexpected property columns")
	}
	ranges := map[string]string{}
	for _, row := range rows[1:] {
		if len(row) != propertyColumns {
			return nil, fmt.Errorf("expected four property columns")
		}
		prefix, _, ok := strings.Cut(row[0], ":")
		if !ok || (prefix != "schema" && prefix != "codemeta") {
			return nil, fmt.Errorf("unknown parent %q", row[0])
		}
		types, err := translate(row[2])
		if err != nil {
			return nil, err
		}
		key := prefix + ":" + row[1]
		for _, typ := range strings.Fields(types) {
			if !contains(ranges[key], typ) {
				ranges[key] = strings.TrimSpace(ranges[key] + " " + typ)
			}
		}
	}
	return ranges, nil
}
func contains(types, typ string) bool {
	for _, v := range strings.Fields(types) {
		if v == typ {
			return true
		}
	}
	return false
}
func translate(expression string) (string, error) {
	var types []string
	for _, name := range strings.Split(expression, " or ") {
		switch name {
		case "Text", "URL", "Number", "Integer", "Boolean", "Date", "Datetime", "ComputerLanguage", "Review", "SoftwareApplication", "CreativeWork", "SoftwareSourceCode", "DataFeed", "Organization", "Person", "MediaObject", "Grant", "PropertyValue", "PostalAddress", "ContactPoint", "ScholarlyArticle":
			types = append(types, name)
		default:
			return "", fmt.Errorf("unsupported property type %q", expression)
		}
	}
	return strings.Join(types, " "), nil
}
